"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DISPOSAL_METHODS = exports.ACTIONS_REQUIRED = exports.WEAR_ZONE_STATUSES = exports.OVERALL_CONDITIONS = exports.INSPECTION_TYPES = exports.LINE_MATERIALS = exports.FUNCTIONAL_POSITIONS = void 0;
var mooring_line_constants_1 = require("./mooring-line.constants");
Object.defineProperty(exports, "FUNCTIONAL_POSITIONS", { enumerable: true, get: function () { return mooring_line_constants_1.FUNCTIONAL_POSITIONS; } });
Object.defineProperty(exports, "LINE_MATERIALS", { enumerable: true, get: function () { return mooring_line_constants_1.LINE_MATERIALS; } });
Object.defineProperty(exports, "INSPECTION_TYPES", { enumerable: true, get: function () { return mooring_line_constants_1.INSPECTION_TYPES; } });
Object.defineProperty(exports, "OVERALL_CONDITIONS", { enumerable: true, get: function () { return mooring_line_constants_1.OVERALL_CONDITIONS; } });
Object.defineProperty(exports, "WEAR_ZONE_STATUSES", { enumerable: true, get: function () { return mooring_line_constants_1.WEAR_ZONE_STATUSES; } });
Object.defineProperty(exports, "ACTIONS_REQUIRED", { enumerable: true, get: function () { return mooring_line_constants_1.ACTIONS_REQUIRED; } });
Object.defineProperty(exports, "DISPOSAL_METHODS", { enumerable: true, get: function () { return mooring_line_constants_1.DISPOSAL_METHODS; } });
